name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/**"
      - "_sams/**"
      - "inbox/**"
      - "_inbox/**"
  schedule:
    - cron: 3 3 15 * *
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Use the club .ics file and stored SBVV IDs to generate individual .ics files
      - name: Create Team Calendars
        run: |
            for team in _teams/*
            do
                this_team_name=$(cat $team | grep title: | sed 's!title: !!')
                this_sbvv_id=$(cat $team | grep sbvv_id: | sed 's!sbvv_id: !!')
                file=$(basename $team)
                filename=$(basename $team .md)
                outputfile=$(echo "_pages/ics_calendar_$filename.html")
                cat "_pages/ics_calendar.html" > $outputfile
                sed -i -e "s#permalink: /ics/all.ics#permalink: /ics/$filename.ics#g" $outputfile
                sed -i -e "s#X-WR-CALNAME:{{ site.name }}#X-WR-CALNAME:{{ site.short_name }}: $this_team_name#g" $outputfile
                if [[ -n $this_sbvv_id ]]; then
                  sed -i -e "s#sbvv_id: none#sbvv_id: $this_sbvv_id#g" $outputfile
                fi
            done

      # Use ImageMagick (bash: convert) to create thumbnail images dynamically
      - name: Create Thumbnails
        run: |
          for file in $(find upload/* -type f)
            do
              if [[ $file == *.jpg ]] || [[ $file == *.jpeg ]] || [[ $file == *.png ]]
                then
                  echo "Processing: "$file
                  
                  news_root=thumbnails/news/
                  gallery_root=thumbnails/gallery/

                  news_file=$(echo $file | sed -e "s!upload/!$news_root!")
                  gallery_file=$(echo $file | sed -e "s!upload/!$gallery_root!")

                  news_folder=${news_file%/*}
                  gallery_folder=${gallery_file%/*}
                  
                  mkdir -p $news_folder
                  mkdir -p $gallery_folder

                  convert "$file" -thumbnail '814x192^' -quality 70 -gravity center -extent '814x192' $news_file
                  convert "$file" -thumbnail '260x200^' -quality 65 -gravity center -extent '260x200' $gallery_file
                fi
            done

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: NPM
        run: npm ci

      - name: Build TinaCMS
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: npx tinacms build

      - name: Build with Jekyll
        id: build_jekyll
        continue-on-error: true
        uses: actions/jekyll-build-pages@v1.0.8
        with:
          source: ./
          destination: ./_site

      - name: Debug Build
        id: verify_build
        continue-on-error: true
        run: |
          ls _site

      - name: Build with Jekyll (Retry)
        id: build_jekyll_retry
        if: steps.verify_build.outcome == 'failure'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
  
  deploy:
      name: Deploy Site
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
