name: SAMS Rankings

concurrency:
  group: sams
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: 44 4 * * * # every night at 4:44
    - cron: 20,40 10-22 * * 6 # once per hour on sa & sun between 10AM - 10PM
  push:
    paths:
      - _spielergebnisse/**

env:
  SAMS_KEY: ${{ secrets.SAMS_API }} # SAMS API key
  SAMS_URL: https://www.volleyball-baden.de # start of the api http structure
  REPO_TARGET: _rankings # the folder I want the output to go to
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}

jobs:
  Get-Teams:
    runs-on: ubuntu-latest
    outputs:
      teamids: ${{steps.teamid-list.outputs.teamids}} # outputs team IDs in the form of [123,456,789]
    steps:
      - name: Get club.xml cache # Get the catched club.xml
        run: curl -o club.xml "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/sams/club.xml"

      - name: Get Team IDs from club.xml
        id: teamids-from-club
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "club.xml"
          xpath: "/sportsclub/teams/team/seasonTeamId" #extract all team IDs from the XML

      - name: Transform MatchSeries IDs
        id: teamid-list
        run: echo "teamids=[${{steps.teamids-from-club.outputs.info}}]" >> $GITHUB_OUTPUT # transform IDs from "123,456,789" to "[123,456,789]"

  Get-MatchSeries-then-Query-SAMS:
    needs: Get-Teams
    continue-on-error: true # if one team fails, the flow should continue
    strategy:
      #max-parallel: 1
      matrix:
        teams: ${{fromJSON(needs.Get-Teams.outputs.teamids)}}
    runs-on: ubuntu-latest
    steps:
      - name: Get club.xml cache # Get the catched club.xml
        run: curl -o club.xml "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/sams/club.xml"

      - name: Get matchSeries IDs from club.xml
        id: matchseriesid-from-club
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "club.xml"
          xpath: "/sportsclub/teams/team[id='${{matrix.teams}}']/matchSeries/id" #extract the matchSeries ID for this team from the XML

      - name: Get rankings.xslt template # Get the xslt template
        run: curl -o rankings.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/sams/rankings.xslt"

      - name: Query SAMS # make the API call to the SAMS server and save it as XML
        run: |
          mkdir -p xml_temp
          curl -o xml_temp/${{matrix.teams}}.xml "$SAMS_URL/xml/rankings.xhtml?apiKey=$SAMS_KEY&matchSeriesId=${{steps.matchseriesid-from-club.outputs.info}}"

      - name: Upload Artifact (SAMS XML) # not needed, only to keep for troubleshooting
        uses: actions/upload-artifact@v3
        with:
          name: raw_sams_xml
          path: xml_temp/${{matrix.teams}}.xml

      - name: Add timestamp to XML # includes a timestamp in German format
        run: sed -i -e 's!</rankings>!<timestamp>'$(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)' Uhr</timestamp></rankings>!g' xml_temp/${{matrix.teams}}.xml

      - name: Transform XML # Push the XML through the XSLT
        run: |
          mkdir -p ${{env.REPO_TARGET}}
          sudo apt-get install xsltproc
          xsltproc rankings.xslt xml_temp/${{matrix.teams}}.xml > ${{env.REPO_TARGET}}/${{matrix.teams}}.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rankings
          path: ${{env.REPO_TARGET}}

  Git-Update:
    needs: Get-MatchSeries-then-Query-SAMS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: rankings
          path: ${{env.REPO_TARGET}}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit Rankings
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.REPO_TARGET}}/*"
          git commit -m "sams scheduled update"

      - name: Git Push
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git pull --rebase
          git push origin --all --quiet